# Generated by Django 3.0.2 on 2020-01-26 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counts',
            old_name='names',
            new_name='name',
        ),
    ]
