# Generated by Django 3.0.2 on 2020-02-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counts', '0002_counts_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='counts',
            name='status',
            field=models.IntegerField(choices=[(1, 'In Progress'), (2, 'Done')], default=1),
        ),
    ]
