# Generated by Django 3.0.2 on 2020-01-26 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answers', '0001_initial'),
        ('questions', '0001_initial'),
        ('counts', '0002_counts_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='answers.Answers')),
                ('count_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='counts.Counts')),
                ('question_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Questions')),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
