# Generated by Django 3.0.2 on 2020-02-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20200208_0755'),
        ('useranswers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswers',
            name='answer_id',
        ),
        migrations.AddField(
            model_name='useranswers',
            name='answer_id',
            field=models.ManyToManyField(blank=True, to='answers.Answers'),
        ),
    ]
