# Generated by Django 3.0.2 on 2020-01-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('text', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
