# Generated by Django 3.0.2 on 2020-02-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='multiple_answers',
            field=models.BooleanField(default=False),
        ),
    ]
